### ISSUE TITLE
Questions about table

### ISSUE THREAD

**Issue by voidfy** [wwu-housing/starterbootstrap#64]
Hello! I have few questions about table.

1. I see your template makes table always 100% width. I am trying to make smaller table so I put '.page table { width: 0 !important; }' this code to override 100% width code in bootstrap.min.css. It worked but when the site goes to mobile mode, 
'div.table, .table-responsive' kicks in and force the table with 100% width resaulting this
![ss](https://cloud.githubusercontent.com/assets/10532647/5932484/d726ee26-a6f1-11e4-82bf-22127270ba17.png)
How can I fix this?

2. Second is question about sortable table.
I am trying to use this function and it works great for number sort but it does not work this alphabe sort

This is orginal screen shot
![original](https://cloud.githubusercontent.com/assets/10532647/5932707/9cf28986-a6f6-11e4-8712-3cb9a0669201.png)

This is alphabet sort. It does not sort alphabetic order. It only flips the table upside down. I tested with uppercase but did not work as well.
![alphabet_sort](https://cloud.githubusercontent.com/assets/10532647/5932709/a53b36ce-a6f6-11e4-9008-918ff17b487a.png)

On the other hand, numeric sort option works great. like this.
![numeric_sort](https://cloud.githubusercontent.com/assets/10532647/5932723/e04c33f8-a6f6-11e4-82f5-cb8c31a46518.png)

I don't know if it's a bug or it suppose to work like this.

Thanks for reading this!

**Comment by apexskier** [comment]
With regard to (1):

I'd suggest using something like the following to get the width what you want:

```css
.dokuwiki table.inline {
  min-width: none;
}
div.table, .table-responsive {
  width: auto;
  border: none;
}
.page table {
  width: 400px;
}
.dokuwiki table.inline {
  border: 1px solid #ddd;
}
```

This is moving the border from the responsive container div to the table itself and is undoing all of the fixed 100% width stuff.
